### ISSUE TITLE
fatal IO error 2 (No such file or directory)

### ISSUE THREAD

**Issue by Johnsonzcode** [likui345/PGA#3]
Dear Likui,
Thank you for your tools. It's a new method to integrate multiple level information of HiFi reads. 
When I came to step `ovlp2graph.py`. It throwed an error.
```bash
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:14.0"
      after 29 requests (27 known processed) with 0 events remaining.
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:14.0"
      after 29 requests (27 known processed) with 0 events remaining.
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:14.0"
      after 29 requests (27 known processed) with 0 events remaining.
```
My command line is 
```bash
ovlp2graph.py --overlap-file pga_best10.paf
# pga_best10.paf is from step 2
```

Sincerely 
Johnsonz

**Comment by matthew-pumc** [comment]
Hi @Johnsonzcode ,
I encountered an error like this, add a line of shebang at the first line of `ovlp2graph.py` could solve this error.

`#!/usr/bin/env python`

best,
Matthew

FYI, the error info is:
```
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
...
ovlp2graph.py: line 10: syntax error near unexpected token `('
ovlp2graph.py: line 10: `class OrderedSet(collections.abc.MutableSet):'
```

**Comment by Johnsonzcode** [comment]
Hi @matthew-pumc ,
Thank you so much, I will try by your information.

best,
Johnsonz

**Comment by Johnsonzcode** [comment]
Hi @matthew-pumc ,
Your way is woking good. But the last step which file should I choose as `--ctg-paths-fn`, there are two ctg path file.
```
sg_edges_list
chimers_nodes
chr_paths
ctg_paths
ctgpath
```
best,
Johnsonz

**Comment by matthew-pumc** [comment]
Hi @Johnsonzcode<https://github.com/Johnsonzcode>,
If you have read the help of the last step, the script will remind you that you should use the chr_paths as:

--chr-paths-fn chr_paths

I think the parameter descripted in readme is inconsistent with what is need by the scripts.

best,
Matthew

On Nov 21, 2022, at 12:15, johnsonz ***@***.***> wrote:



Hi @matthew-pumc<https://github.com/matthew-pumc> ,
Your way is woking good. But the last step which file should I choose as --ctg-paths-fn, there are two ctg path file.

sg_edges_list
chimers_nodes
chr_paths
ctg_paths
ctgpath


best,
Johnsonz

**Comment by Johnsonzcode** [comment]
> 

Thank your for your kind help. Yes, I found this option in scripts. I am waiting for the results.

**Comment by Johnsonzcode** [comment]
Dear @matthew-pumc ,
The result `p_ctg.fasta` seems not the final chrmosome. How could I get final chromosome ?
best,
Johnsonz

**Comment by matthew-pumc** [comment]
Hi Johnsonz,
I’m afraid this result is the final chromosome, and I got a decent assembly in this file.

Best
Matthew

**Comment by Johnsonzcode** [comment]
Dear @matthew-pumc ,
How you tune the parameter, such as `--best-n`, minimum initial contigs length?
best,
Johnsonz

**Comment by matthew-pumc** [comment]
Hi Johnsonz,
I did not tried my own data, I just used the data from this author’s article and set –best-n to 5
Then I have 12 chromosomes.
I am going to use my own data this week, hope that I can get a great result.

Best,
Matthew

**Comment by Johnsonzcode** [comment]
Hi @matthew-pumc ,

Testing from article data is a good way. Hope you I can get a great result. BTW, what your data type? Only HiFi data ?

best,
Johnsonz

**Comment by Johnsonzcode** [comment]
Hi @matthew-pumc ,
Actually, I got several decent chromosome from PGA, but not every chromosome. It is Exciting. Do you have wechat or something like that, maybe we can communicate assembly method on wechat?

**Comment by matthew-pumc** [comment]
you can search my id: matthew_hawking
